name: Build Backend Docker Image
permissions:
  contents: read
  packages: write
on:
  push:
jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yaml
  test-backend:
    runs-on: self-hosted
    needs: build-backend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Start backend env
        run: |
          docker compose --profile ci up --build
      - name: Run unitests
        run: |
          docker exec -it mkdi-backend pytest /backend
      - name: Run functinal tests
        run: |
          docker exec -it mkdi-backend pytest /mkdi-shared
      - name: Run behave tests
        run: |
          docker exec -it mkdi-backend behave /functional-tests/features
  build-backend:
    needs: pre-commit
    uses: ./.github/workflows/docker-build.yaml
    secrets: inherit
    with:
      image-name: mkdi-backend
      context: .
      dockerfile: docker/Dockerfile.backend
      build-args: ""
