name: Build Backend Docker Image
permissions:
  contents: read
  packages: write
on:
  push:
jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yaml
  build-backend:
    uses: ./.github/workflows/docker-build.yaml
    needs: pre-commit
    with:
      image-name: mkdi-backend
      context: .
      dockerfile: docker/Dockerfile.backend
      build-args: ""
