name: Build Backend

on:
    push:
jobs:
    pre-commit:
        uses: ./github/workflows/pre-commit.yaml
    build-backend:
        uses: ./github/workflows/build-docker.yaml
        needs: pre-commit
        with:
            image-name: mkdi-backend
            context: .
            dockerfile: docker/Dockerfile.backend
            build-args: ""