name: Docker Build

on:
  push:
  workflow_call:
    inputs:
      dockerfile:
        required: true
        type: string
      context:
        required: true
        type: string
      image-name:
        required: true
        type: string
      build-args:
        required: false
        type: string
jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Login to container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ secrets.M_USERNAME }}
          password: ${{ secrets.M_GITHUB_TOKEN }}
      - name: Get Base registry
        run: |
          echo "REGISTRY=ghcr.io/${M_GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
      - name: Set tag prefix
        if: github.ref_name != 'main'
        run : /
          echo "TAG_PREFIX=${{ github.ref_name}}-" >> $GITHUB_ENV