name: Docker Build

on:
  workflow_call:
    inputs:
      dockerfile:
        required: true
        type: string
      context:
        required: true
        type: string
      image-name:
        required: true
        type: string
      build-args:
        required: false
        type: string
jobs:
  build:
    name: Build Images
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Set tag prefix
        if: github.ref_name != 'main'
        run: |
          echo "TAG_PREFIX=${{ github.ref_name }}-" >> $GITHUB_ENV
      - name: Extract ticket number
        id: extract
        if: github.ref_name != 'main'
        run: |
          echo "PROJECT_INITIAL=$(echo ${{github.ref_name}} | cut -d'-' -f1)"
          echo "TICKET_NUMBER=$(echo ${{github.ref_name}} | cut -d'-' -f2)"
          echo "::set-output name=image_tag::${PROJECT_INITIAL}-${TICKET_NUMBER}"
      - name : Build docker images on local runner
        uses: docker/build-push-action@v3.2.0
        with:
            file: ${{ inputs.dockerfile }}
            context: ${{ inputs.context }}
            build-args: ${{ inputs.build-args }}
            push: false
            load: true
            tags: ${{ steps.extract.outputs.image_tag }}
            # labels: ${{ steps.meta.outputs.labels }}
            cache-from: type=gha
            cache-to: type=gha,mode=max