name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy-to-prod:
    uses: ./.github/workflows/deploy-to-node.yaml
    secrets: inherit
    with:
      stack-name: staging
      image-tag: latest
      backend-port: 8280
      website-port: 3200
